### ISSUE TITLE
run a script on boot?

### ISSUE THREAD

**Issue by protobruce** [showmewebcam/showmewebcam#107]
Hi, I'm wondering how I could run a python script when booting the device to run peripherals to the cam.
For my use case, I am thinking about running a simple single-mode led video flash (using Blinkt, or Pimoroni Unicorn Hat or Mote) and want to run it off the same Zero. Is it possible given the this is really just plug and play?

**Comment by dgsiegel** [comment]
Sure, you can add whatever script you like, have a look at how we start the piwebcam services (`package/piwebcam/*.service`). Oh and you'd have to add python support in Buildroot, but that's just a simple dependency.
