### ISSUE TITLE
Add my case on to the wiki?

### ISSUE THREAD

**Issue by smartroad** [showmewebcam/showmewebcam#108]
Wanted to ask if it would be okay to add my 3D Printable case on the wiki? My design uses the ZeroCam rather than the HQ Cam and is designed to clip onto a monitor (https://www.prusaprinters.org/prints/57680-pizero-webcam)

**Comment by htruong** [comment]
Thanks for the contribution. From what I understand, you should be able to edit the wiki. 

Please feel free to edit the wiki, I am very open to everyone editing the wiki. If you can't, please let us know.

I am also very happy to do it for you :)
