### ISSUE TITLE
Can´t enable networking

### ISSUE THREAD

**Issue by Lippsson** [showmewebcam/showmewebcam#111]
Hello!
Thanks for the great work and code. Its was really simple to make it happend with my raspberz zero w and hq sensor. Now i want to change some setting (for example test how 1080p with 30fps work) and find some instructions in the Wiki ->Networking (On Windows)
I am on the point where i add the 2 file (Disable-webcam) and (enable-usb-network) the /boot partition, but it shows the webcam anyway. 

![image](https://user-images.githubusercontent.com/48052340/109320706-98ba6000-7850-11eb-8766-6f4aad32cbdf.png)

Can you please help me out here? (I have win10 version 20H2)
Thank you

**Comment by htruong** [comment]
I'm yet to merge the patch that enables networking, so stay tuned :)

**Comment by htruong** [comment]
https://github.com/showmewebcam/showmewebcam/pulls
