### ISSUE TITLE
enable-serial-debug not present under /boot

### ISSUE THREAD

**Issue by oculos** [showmewebcam/showmewebcam#114]
Hi,

On the instructions it is said that the file `enable-serial-debug` should be removed off from the `/boot` folder - but I can't see it there. Has this been deprecated? Any other security measure that should be taken?

Best,
Francis

**Comment by dgsiegel** [comment]
You can find it in master (https://github.com/showmewebcam/showmewebcam/commit/214b21ac04df15518cf5fb674d5859e2133903ee) and will be in the upcoming release.
