### ISSUE TITLE
UVC controls missing on Linux and Mac compared to windows.

### ISSUE THREAD

**Issue by taprobane99** [showmewebcam/showmewebcam#122]
I built showmewebcam from Master, and on my Pi zero with hq cam I get the following:

Webcamoid windows: brightest, contrast, saturation, sharpness (sliders). exposure (auto) (checkbox)
Webcamoid Linux: brightness, contrast, saturation (sliders). (also same in v4l command line)
Webcamoid Mac: no controls!

On all 3 machines the webcam works ok in Zoom. Perhaps Zoom doesn't care about UVC.

Why is there a difference between the UVC controls exposed and could it be fixed?

Also, I noticed in the build directory there is:
showmewebcam/patches/linux-custom/0001-linux-enable-more-video-controls.patch

Is this actually compiled in? and if not, is there a way to compile in that patch at build time?

**Comment by htruong** [comment]
>Also, I noticed in the build directory there is:
>`showmewebcam/patches/linux-custom/0001-linux-enable-more-video-controls.patch`
>
>Is this actually compiled in? and if not, is there a way to compile in that patch at build time?

Yes, it is integrated in every build: https://github.com/showmewebcam/showmewebcam/blob/master/configs/config#L45

I will look at the Mac issue...
