### ISSUE TITLE
Confusion about auto exposure mode values

### ISSUE THREAD

**Issue by taprobane99** [showmewebcam/showmewebcam#123]
video quality is great during the daytime with my pi hq + 6mm lens.

If I set auto_exposure=1 in camera.txt I get slightly better quality than the default of auto_exposure=0 in the evening/dim lighting.

on the camera-ctl UI 1 is labelled "manual", but according to the UVC standard 1 is auto.

can someone clarify whether 0 or 1 is auto, and if 1 is better should this be the default?

<img width="537" alt="105799532-c6b33880-5f62-11eb-913b-e8a90513aa9d" src="https://user-images.githubusercontent.com/57266492/113519530-c055c400-9584-11eb-9397-e693b6448531.png">

**Comment by dgsiegel** [comment]
We'd be happy to adjust the defaults if they bring better results, feel free to open a PR.

For the UVC standard you might need to open an issue for https://github.com/peterbay/uvc-gadget, as those things are set up there.

**Comment by taprobane99** [comment]
On further investigation I think 0 (the default) is automatic and 1 is manual. It just differs from the UVC convention.

Will close this.
