### ISSUE TITLE
There are idiots like me who will connect their camera cable to the display output

### ISSUE THREAD

**Issue by RichardBronosky** [showmewebcam/showmewebcam#130]
This sarcastic issue is more of a confession than a request for change. I’m doing this to comfort people with the knowledge that [even a developer who has written an alternative init executable for the RPi](https://github.com/RichardBronosky/pi-init2/blob/master/src/pi-init2/init.go) can make such a boneheaded mistake.

I worked way past exhaustion last weekend compiling this repo multiple times using BuildRoot on an RPi4, and on a Core i7 both in a Vagrant VM and a Docker container. If I  would have gotten some sleep I would have been more likely to notice why the Kernel never recognized the device.

**Comment by htruong** [comment]
Haha, well [sometimes it happens](https://youtu.be/V-pK8SfXdFY?t=59).
