### ISSUE TITLE
max resolution

### ISSUE THREAD

**Issue by natxopedreira** [showmewebcam/showmewebcam#149]
Hello

I saw here a list of resolutions is possible to set with a HQ camera to max resolution even lowering fps of course, only to take stills for example

[https://github.com/showmewebcam/showmewebcam/blob/1678d4b578c9522068cb5d9312f593a93760f63a/package/piwebcam/multi-gadget.sh#L64](https://github.com/showmewebcam/showmewebcam/blob/1678d4b578c9522068cb5d9312f593a93760f63a/package/piwebcam/multi-gadget.sh#L64)

Thanks!

**Comment by htruong** [comment]
Sorry I'm not sure what your question is. Mind to elaborate?

**Comment by natxopedreira** [comment]
Sorry, basically whats the max resolution as in mmal can get 4046*3040 and i only saw up to 1080 in that file

**Comment by dgsiegel** [comment]
MMAL can in fact get 4046*3040 but only for still photos, for video 1080p is our current maximum.
