### ISSUE TITLE
Different Apps, Different Resolutions - Mac OS

### ISSUE THREAD

**Issue by phenomeus** [showmewebcam/showmewebcam#160]
Hi :) 

I updated to 1.90 and tested again some of my app to see if every app is using 1080p max on my RPI Zero W.
camera-ctl is telling me the following on macOS 11.6 
Teams - 640x320
Chrome Meet - 1280x720
Skype for Business - 1920x1080 

is there a way to tell every app use 1080p?

**Comment by dgsiegel** [comment]
Hey, yeah this is possible: https://github.com/showmewebcam/showmewebcam#configure-available-camera-resolutions-and-streaming-format
