### ISSUE TITLE
Neither WebCam nor serial TTY decide shows, what next?

### ISSUE THREAD

**Issue by islaeh** [showmewebcam/showmewebcam#162]
Hardware check: The combination of Pi Zero WH and HQ Cam from Raspi *does* work with OS image "2021-05-07-raspios-buster-armhf-lite" and testing locally via raspistill (I can take an image as JPEG) while connected via WiFi to the Raspi Zero. 
The board and the camera are therefore OK.

If I however boot the OS image "sdcard-raspberrypi0w-v1.90", I do not see the expected USB camera (e.g. in Zoom oder WebEx). The Raspi Zero + HQ Webcam is connected with USB to Mac (2nd USB port used, *not* the outer Power-USB Port on the Raspi) . The good news is: the LED blinks in three times (last blink consists of three shorter blinks).

I tried to use the the command on MacOS
`ls -l /dev/tty*`
to see which serial interface to connect to... but there is not the tty.usbmodem13103 showing up. The output does not differ between connected vs. disconnected Raspi Zero. No change, if alternative USB cable is used (i.e. USB cable is OK)

No Camera visible, no TTY device, what shall be my next steps to narrow down the source of the error?

**Comment by islaeh** [comment]
I'm on Big Sur 11.6. The ShowMeWebCam version is 1.90.

I've tried it on Pi Zero (no "W") with the smaller 8 MP camera - no change to above situation.

**Comment by islaeh** [comment]
Partially SOLVED: Two USB-cables were not working, the third showed the UVC cam as expected. 
I tested with two shorter cables (mainly for charging) and one longer (which then worked). My solution is to try a *longer* USB-cable if you can't get the cam to work,

**Comment by islaeh** [comment]
Use correct (longer) USB-cable for showmewebcam to work

**Comment by hrlai** [comment]
Hi although this is closed, just thought to note: also make sure to plug in the mini USB port on your Pi that says "USB", not "PWR IN"
