### ISSUE TITLE
Unable to change camera parameters

### ISSUE THREAD

**Issue by 9j7axvsLuF** [showmewebcam/showmewebcam#17]
Hello,

First of all thanks for your work on this great repo! I had no issue getting the webcam up and running, it was very easy.

Hopefully the image I get is quite dark, so I'd like to mess with the camera settings to improve the quality of the output.

I tried connecting the microsd card to my laptop to create "camera.txt" in /boot, but I get an error message telling me that the partition is read-only. By the way, I get two partitions when I connect the microsd card, and the one in which /boot is shows up as a squashfs partition which - as I understand it - is always read-only.

Would you be able to help me?

Many thanks in advance!

**Comment by tuyenld** [comment]
Hi @9j7axvsLuF 
> I tried connecting the microsd card to my laptop to create "camera.txt" in /boot, but I get an error message telling me that the partition is read-only
You can follow the instruction on README to create "camera.txt"
```bash
#You can edit camera.txt on-target by remounting /boot read-write:

mount -o remount,rw /boot
```
As you can see here https://github.com/showmewebcam/showmewebcam/blob/master/board/raspberrypi0cam/genimage-raspberrypi0cam.cfg only rootfs partition is read-only. Which image did you use?

**Comment by 9j7axvsLuF** [comment]
Thanks a lot! It turns out I was trying to create the file camera.txt in the front partition (because I saw that the 30MB rootfs partition contained a /boot directory, and I thought it had to be in that directory).

It seems to work now!
