### ISSUE TITLE
getting error while building image file as mentioned in Development & building section

### ISSUE THREAD

**Issue by Parikshit01** [showmewebcam/showmewebcam#175]
While following the mentioned steps in the repo's Development & building section, After running` ./build-showmewebcam.sh raspberrypi0w` command i'm getting below error.
```
>>>   Executing post-image script /home/parikshit/showmewebcam/board/post-image.sh
grep: /home/parikshit/showmewebcam/output/raspberrypi0w/images/rpi-firmware/config.txt: No such file or directory
INFO: cmd: "mkdir -p "/home/parikshit/showmewebcam/output/raspberrypi0w/build/genimage.tmp"" (stderr):
INFO: cmd: "rm -rf "/home/parikshit/showmewebcam/output/raspberrypi0w/build/genimage.tmp"/*" (stderr):
INFO: cmd: "mkdir -p "/home/parikshit/showmewebcam/output/raspberrypi0w/build/genimage.tmp"" (stderr):
INFO: cmd: "cp -a "/tmp/tmp.gv4rB9nO6S" "/home/parikshit/showmewebcam/output/raspberrypi0w/build/genimage.tmp/root"" (stderr):
INFO: cmd: "find '/home/parikshit/showmewebcam/output/raspberrypi0w/build/genimage.tmp/root' -depth -type d -printf '%P\0' | xargs -0 -I {} touch -r '/tmp/tmp.gv4rB9nO6S/{}' '/home/parikshit/showmewebcam/output/raspberrypi0w/build/genimage.tmp/root/{}'" (stderr):
ERROR: file(rpi-firmware/bootcode.bin): stat(/home/parikshit/showmewebcam/output/raspberrypi0w/images/rpi-firmware/bootcode.bin) failed: No such file or directory
ERROR: vfat(boot.vfat): could not setup rpi-firmware/bootcode.bin
make[1]: *** [Makefile:823: target-post-image] Error 1
make: *** [Makefile:23: _all] Error 2
make: Leaving directory '/home/parikshit/showmewebcam/output/raspberrypi0w'

```

kindly let me know the possible reason and solution for this.
All the previous parts are running error-free

**Comment by Parikshit01** [comment]
output of `./build-showmewebcam.sh raspberrypi0` is as below
`grep: /home/parikshit/showmewebcam/output/raspberrypi0/images/rpi-firmware/config.txt: No such file or directory
INFO: cmd: "mkdir -p "/home/parikshit/showmewebcam/output/raspberrypi0/build/genimage.tmp"" (stderr):
INFO: cmd: "rm -rf "/home/parikshit/showmewebcam/output/raspberrypi0/build/genimage.tmp"/*" (stderr):
INFO: cmd: "mkdir -p "/home/parikshit/showmewebcam/output/raspberrypi0/build/genimage.tmp"" (stderr):
INFO: cmd: "cp -a "/tmp/tmp.WXdBngpahk" "/home/parikshit/showmewebcam/output/raspberrypi0/build/genimage.tmp/root"" (stderr):
INFO: cmd: "find '/home/parikshit/showmewebcam/output/raspberrypi0/build/genimage.tmp/root' -depth -type d -printf '%P\0' | xargs -0 -I {} touch -r '/tmp/tmp.WXdBngpahk/{}' '/home/parikshit/showmewebcam/output/raspberrypi0/build/genimage.tmp/root/{}'" (stderr):
ERROR: file(rpi-firmware/bootcode.bin): stat(/home/parikshit/showmewebcam/output/raspberrypi0/images/rpi-firmware/bootcode.bin) failed: No such file or directory
ERROR: vfat(boot.vfat): could not setup rpi-firmware/bootcode.bin
make[1]: *** [Makefile:823: target-post-image] Error 1
make: *** [Makefile:23: _all] Error 2
make: Leaving directory '/home/parikshit/showmewebcam/output/raspberrypi0'

`

**Comment by dgsiegel** [comment]
Which buildroot version did you use? Wanna try with an older stable, 2021.02.4? 

Buildroot is currently restructuring a few things related to the Raspberry and we haven't catched up yet, waiting for #173

**Comment by Parikshit01** [comment]
thanks. solved with the latest stable repo.
I was cloning buildroot latest Github repo which was probably not a stable release.
