### ISSUE TITLE
IP Camera Solution 

### ISSUE THREAD

**Issue by Parikshit01** [showmewebcam/showmewebcam#176]
is it possible to use RPi4 with RPI HQ Camera as IP Camera? 
I was looking forward to using multiple of these setups to be connected with a Switch/Router and use my laptop being in same local network to do multiple camera-based image processing.

**Comment by dgsiegel** [comment]
Yes that would be possible, but not with Showme Webcam, as we have removed all networking functionality. But I've seen some other projects and forum entries doing exactly that.
