### ISSUE TITLE
High CPU usage after streaming

### ISSUE THREAD

**Issue by Janghou** [showmewebcam/showmewebcam#178]
CPU usage Zero (W):

- After boot (idle): < 5%
- Streaming: ~ 70%
- After stream has stopped (idle again): ~ 55%

Reported by top for `/opt/uvc-webcam/uvc-gadget`

Tested on Ubuntu (21.10)

**Comment by okawo80085** [comment]
Would be nice to see some sort of work around/solution to this, in my case the rpi stays plugged in indefinitely, i don't want to waste more power when the device is idle, i use it in a VR system, wasting power is the last thing i need. If its possible to enforce that state via serial commands that works for me too.

**Comment by dgsiegel** [comment]
You might want to report this to https://github.com/peterbay/uvc-gadget

**Comment by okawo80085** [comment]
> You might want to report this to https://github.com/peterbay/uvc-gadget

Will do just that, thanks :)
