### ISSUE TITLE
Images don't build

### ISSUE THREAD

**Issue by jim-cathey** [showmewebcam/showmewebcam#180]
I followed the given directions, and downloaded the 191 sources, and put buildroot 2021.11 in it, as "buildroot", and ran "./build-showmewebcam.sh raspberrypi0".  (This is on LUbuntu 20.04.3 LTS, in a VMware VM on an older Mac Pro.  [Intel x64])  It chugged for 90 minutes, then failed with:
<PRE>
...
ERROR: file(rpi-firmware/bootcode.bin): stat(/home/jimc/showmewebcam-master/output/raspberrypi0/images/rpi-firmware/bootcode.bin) failed: No such file or directory
ERROR: vfat(boot.vfat): could not setup rpi-firmware/bootcode.bin
make[1]: *** [Makefile:823: target-post-image] Error 1
make: *** [Makefile:23: _all] Error 2
make: Leaving directory '/home/jimc/showmewebcam-master/output/raspberrypi0'
</PRE>
There was no output image, of course.  The same problem occurs with a raspberrypi0w target.  The raspberrypi4 target fails similarly:
<PRE>
...
ERROR: file(rpi-firmware/fixup.dat): stat(/home/jimc/showmewebcam-master/output/raspberrypi4/images/rpi-firmware/fixup.dat) failed: No such file or directory
ERROR: vfat(boot.vfat): could not setup rpi-firmware/fixup.dat
make[1]: *** [Makefile:823: target-post-image] Error 1
make: *** [Makefile:23: _all] Error 2
make: Leaving directory '/home/jimc/showmewebcam-master/output/raspberrypi4'
</PRE>

**Comment by dgsiegel** [comment]
Currently, you'd need the LTS (2021.02.8) or an earlier stable release (see https://github.com/showmewebcam/showmewebcam/blob/master/.github/workflows/release.yml#L23). The latest stable Buildroot release changed some things regarding how we build our images and we haven't catched up yet.
