### ISSUE TITLE
No Webcam/Serial with Pi Zero 

### ISSUE THREAD

**Issue by carrefinho** [showmewebcam/showmewebcam#192]
Hello,

I'm having trouble getting my Raspberry Pi Zero v1.3 to work. It appears to boot and flash its LED three times roughly 15 seconds after power is connected. However, neither a camera nor serial device show up on both my Macbook Pro(macOS 12.3) and Windows 10 desktop PC.

I'm sure the image version is correct and I tried multiple different SD cards. Another Pi Zero WH v1.1 works perfectly with the same camera(official V2.1 8MP) and cable.

**Comment by dgsiegel** [comment]
Flashing three times means that it is fully booted up and the camera works. In most cases it's either the wrong port (one is data, one is only current) or a faulty cable. Actually, in almost all cases it's a faulty cable. So try with different cables until you find one which works.

**Comment by JustJoshingYa** [comment]
I'm having this problem too, but only the camera feed does not show up. I've checked the cables and pi and they do transmit data and receive but the camera does not pop up.

**Comment by JustJoshingYa** [comment]
I should probably mention it's also a Pi Zero WH v1.1

**Comment by davealexis** [comment]
Trying this on a Raspberry Pi Zero (no WiFi). When the cable is connected, the Pi's power LED blinks twice, not 3 times, and nothing happens.

**Comment by dgsiegel** [comment]
Please try a different cable and make sure the camera cable is connected well. Also see https://github.com/showmewebcam/showmewebcam/wiki/FAQ#my-raspberry-pi-doesnt-work
