### ISSUE TITLE
Boot from USB device instead of sd card?

### ISSUE THREAD

**Issue by cjheppell** [showmewebcam/showmewebcam#198]
I've tried booting from an RPI 4 with the image written to a USB drive.

However, it fails to boot.

After the rainbow screen, there is just a blinking cursor when viewing the HDMI output.

Using an SD card works just fine though. Is there a config setting you can point me to so that the Pi knows to boot from the USB device instead of the sd card?

(For context - the reason I'd like this is because the sd card slot on my Pi 4 is broken :sweat_smile:)

**Comment by dgsiegel** [comment]
Check this out: https://github.com/Janghou/showmewebcam-usbboot

**Comment by cjheppell** [comment]
Forgive me if I'm wrong, but it seems that example requires the usbboot program on the "host" computer to launch showmewebcam on the Pi?

That's not quite what I'm hoping for. Ideally, I'd like to be able to boot directly from usb without manual steps, just as booting from sd works.

I can do this with Raspberry Pi OS just fine. It would be great if showmewebcam offered a similar capability.
