### ISSUE TITLE
Design a simple laser cut sandwich piece for the HQ camera and Pi0

### ISSUE THREAD

**Issue by htruong** [showmewebcam/showmewebcam#21]
Would any kind soul with some CAD skill design a acrylic piece to sandwich between the camera and the raspberry pi board so they don't move?

I'm thinking of the following simple requirements:
- Has 4 holes to hold the pi and 4 holes to hold the HQ camera. Camera is in the front of the Pi like picture attached. Works for the short ribbon cable.
- Allows the HQ camera to be mounted with a camera tripod piece, so the Pi cannot be too low because that will bend the flex cable.

![sandwich](https://user-images.githubusercontent.com/146489/97098291-87f6a500-1638-11eb-8654-7dcfc447de2a.jpg)

(If you have one and can send my way, that'd be extra appreciated!)

**Comment by miip** [comment]
I 3d printed this https://www.thingiverse.com/thing:4445767

Works great

**Comment by dgsiegel** [comment]
Or buy this one: https://thepihut.com/products/mounting-plate-for-high-quality-camera

**Comment by htruong** [comment]
Thanks @dgsiegel I didn't know that they offer this piece for sale, it's exactly what I wanted!
