### ISSUE TITLE
Not showing up on M1 pro Mac

### ISSUE THREAD

**Issue by kenknoll** [showmewebcam/showmewebcam#216]
Hey folks, this used to work great on my older MBP, but not on my newer model (M1 pro). Tried all kinds of cables. Shows up in USB devices, but not as a camera. Only hint I got is that the UVC config might be wrong: https://developer.apple.com/forums/thread/693784

Appreciate any help!

**Comment by kenknoll** [comment]
I should note I can indeed connect through the ttyACM console.

**Comment by dgsiegel** [comment]
This looks very familiar to https://github.com/showmewebcam/showmewebcam/issues/164

Are you using the latest image? Although it's strange that you can connect through the ttyACM console...

**Comment by kenknoll** [comment]
You're absolutely right, the new release fixed this - thanks!
