### ISSUE TITLE
Add camera.txt to /boot during build

### ISSUE THREAD

**Issue by dgsiegel** [showmewebcam/showmewebcam#23]
It would be awesome if an existing camera.txt could be copied to /boot when building an image yourself. With that in place, we could also remove 

```
/usr/bin/v4l2-ctl -c auto_exposure_bias=3
/usr/bin/v4l2-ctl -c video_bitrate=25000000
```
from `package/piwebcam/start-webcam.sh`. The only solution I found would be to add the camera.txt file to `board/raspberrypi0cam/genimage-raspberrypi0.cfg` and add these lines to `board/raspberrypi0cam/post-image.sh`:

```
# Copy camera.txt if it exists in build dir
if [ -f "${BR2_EXTERNAL_PICAM_PATH}/camera.txt" ]; then
  cp "${BR2_EXTERNAL_PICAM_PATH}/camera.txt" "${BINARIES_DIR}/rpi-firmware/camera.txt"
fi
```

But that requires an existing camera.txt in the root folder or the build will fail.

**Comment by htruong** [comment]
Not that I tested this idea, but we could put a dummy blank `camera.txt` file in the repo so that it doesn't upset the `cfg` file config, and then somehow dynamically swap it to the real file to it during build, maybe?

**Comment by dgsiegel** [comment]
That would work if we add the above mentioned camera.txt file to the repo. Don't know if that is the best way though...

**Comment by PSF1** [comment]
The repo has a camera.txt.example in it. That file have configuration details but it don´t change default values. it maybe copied how a empty camera.txt file while building.

**Comment by dgsiegel** [comment]
Well, we already have these two lines in `package/piwebcam/start-webcam.sh`:
```

/usr/bin/v4l2-ctl -c auto_exposure_bias=3
/usr/bin/v4l2-ctl -c video_bitrate=25000000
```

They could easily go into the default camera.txt, no?

**Comment by dgsiegel** [comment]
Here's a pull request for this: https://github.com/showmewebcam/showmewebcam/pull/31

**Comment by rcarmo** [comment]
It would be nice to have a sample `camera.txt` by default with the most common settings there (including rotation, which is what I need to tweak on every new build...).

**Comment by dgsiegel** [comment]
Yeah, we have some settings already (https://github.com/showmewebcam/showmewebcam/issues/23#issuecomment-723344994). What other settings would you propose?

Regarding rotation, that probably depends on how you use your mount?

**Comment by rcarmo** [comment]
I don’t have a standard mount (I built my own compact mount, which is depicted in https://taoofmac.com/space/blog/2020/10/11/1800 <https://taoofmac.com/space/blog/2020/10/11/1800> and requires me to set the rotation to 270).

I would say that brightness, contrast and quality/bitrate would be among the top 5 things to have available by default...

**Comment by dgsiegel** [comment]
Oh ok. I guess not that many people will have their camera mounted at 270 degrees :) Do you build the image yourself? In either case you can set defaults, which won't get overwritten.

Brightness and contrast are set to auto right now. The quality/bitrate to max as seen above.

**Comment by rcarmo** [comment]
No, I just shove a camera.txt in after flashing the image. Would be nice to have one there, though. Quicker to edit :)

**Comment by dgsiegel** [comment]
Well with my PR you can have your camera.txt in your showmewebcam directory and have it copied over automatically. I can't really think of a solution when flashing the image though...

**Comment by rcarmo** [comment]
Nah, I just want a set of sensible defaults inside the image. I just flashed the latest, and even the .sample file would have come in handy in there.

**Comment by dgsiegel** [comment]
Alright. Could you try the following settings? I've tried them locally and they seem to provide a good, average result:

```
auto_exposure=0
auto_exposure_bias=12
contrast=-2
saturation=5
video_bitrate=25000000
sharpness=20
```

**Comment by dgsiegel** [comment]
@htruong would you mind trying these defaults on your 6mm lens?

**Comment by htruong** [comment]
My picture with the default settings on a bright day:

![piwebcam-default](https://user-images.githubusercontent.com/146489/99914286-2fefa480-2cb1-11eb-8f55-b5cadcff5d9d.jpeg)


I actually have my camera.txt to be so:

```
auto_exposure_bias=15
contrast=0
brightness=55
```

Then my picture is way better:

![piwebcam-tweaked](https://user-images.githubusercontent.com/146489/99914290-33832b80-2cb1-11eb-9636-73294628a03b.jpeg)

What do you think about this setting?

**Comment by htruong** [comment]
Your settings:

![ppiwebcam-dgsiedel](https://user-images.githubusercontent.com/146489/99914344-9eccfd80-2cb1-11eb-9121-79f2295d249f.jpeg)

**Comment by htruong** [comment]
Let's use yours as default.
