### ISSUE TITLE
Unable to boot/detect Raspberry Pi Zero (no W) with showmewebcam

### ISSUE THREAD

**Issue by Andersang** [showmewebcam/showmewebcam#230]
For some reason I'm unable to get the RPi Zero (no W) to boot even with the latest correct image, ```sdcard-raspberrypi0-8e9f9ac.img```. 

For context: 
I used to run showmewebcam on an RPi Zero (no W) about 2 years ago with an old Raspberry Pi Camera Rev 1.3. It worked fine for awhile until I accidentally ripped the camera's ribbon cable, left it in a sealed box and forgot about it for 2 years. I found the old setup recently, got a new ribbon cable, and I followed the old [instructions](https://web.archive.org/web/20220901000000*/https://tutorial.cytron.io/2020/12/29/raspberry-pi-zero-usb-webcam/) to the dot - but with the latest image specified. 

This time round however, when connecting the RPi Zero to the PC (new fresh Win11 install), the RPi Zero's LED flashes once, the connected camera's LED Flashes once, RPi Zero's LED flashes once more, the connected camera's LED Flashes once again, and then nothing happens afterwards. My PC doesn't seem to detect any new device, which means I can't even check the RPi's status through the serial monitors (I tried a few). This does not seem to be a PC issue, as I tried the same thing with my old Macbook Pro, the same one I used with the previous setup, and had no results as well. I removed ```initial_turbo``` as mentioned somewhere in the docs, changed usb ports, changed usb cables (those I knew worked with other microcontrollers), changed microSD cards... no results.

In issue #95, there was a comment about v1.40 working for them - I tried flashing v1.40 to the microSD card, and now the RaspberryPi boots - but Windows 11 doesn't detect it anywhere. MacOS on a separate computer does not detect it as well. I still can't see any additional com ports. The light on the camera module momentarily lights up so at least I know the ribbon cable should be working. 

Does anyone have any idea what might be going on?

**Comment by htruong** [comment]
Hey, sorry for the late reply. This most likely means that your usb cable doesn't have data pins connected correctly. You need to have a good usb cable, and connect it to the middle port of the pi (not the outer port).
