### ISSUE TITLE
[Feature] Enable GPIO pin on webcam stream

### ISSUE THREAD

**Issue by Leonti** [showmewebcam/showmewebcam#30]
One feature that was missing for me was the lack of LED to indicate that the camera is streaming.
I've done it locally and it works well, here is the picture of the camera when streaming:
![](https://raw.githubusercontent.com/Leonti/rpi-hq-camera-case/master/photos/assembled.jpg)

I've modified my local copy of https://github.com/showmewebcam/uvc-gadget to do that (enable pin 21 when streaming starts and disable when streaming ends) and was about to make a PR, but it seems like the project will be moving to https://github.com/peterbay/uvc-gadget soon.  

Which repo would be best to submit a PR?

**Comment by peterbay** [comment]
Put your local copy to github and i will implement it to my version of uvc-gadget

**Comment by peterbay** [comment]
I've created room at discord for discussion about uvc-gadget - https://discord.gg/EN7AJNw5

**Comment by Leonti** [comment]
Hi @peterbay!
That would be awesome!

Here is the code I'm running at the moment:
https://github.com/showmewebcam/uvc-gadget/compare/master...Leonti:gpio-21?expand=1

**Comment by dgsiegel** [comment]
Seems like this was done https://github.com/peterbay/uvc-gadget/commit/bf1b5fba283d1b08f8616a9d3c1567b4eeca9d20. It also works with the onboard led: https://github.com/peterbay/uvc-gadget/commit/ad13e70614433327be74b7f19fb7774f8cb9d08d

**Comment by htruong** [comment]
I'm closing this issue due to its spirit being implemented. :)
