### ISSUE TITLE
Coil whining and strange artifacts

### ISSUE THREAD

**Issue by greimela** [showmewebcam/showmewebcam#47]
Hi, thanks for this awesome project!
It was really easy to set it up on an Pi Zero W.

Is it normal that the Pi is whining as soon as the camera is active?

Also, after a couple of seconds I receive artifacts like these.
![Screen Shot 2020-11-26 at 17 01 24](https://user-images.githubusercontent.com/11612483/100372506-9bb37380-3009-11eb-94ff-a86aaaf23c99.png)

Any ideas what could be the reason for that or how to debug it?

**Comment by dgsiegel** [comment]
I've never had any noise issues with my Pi. However I once noticed similar artifacts on a USB hub. Would you mind trying either a different cable or plugging the Pi directly into your computer?

**Comment by greimela** [comment]
Thanks for the hint.

I tried it on a MacBook using an USB-C hub. And now I also tried it directly plugged into a Windows laptop. 

On both devices these artifacts appear after some seconds and the number of artifacts grows over time.

**Comment by dgsiegel** [comment]
Would you mind reporting this to https://github.com/peterbay/uvc-gadget? It's the backend we use, and this looks like a hardware bug mostly

**Comment by greimela** [comment]
Will do, thanks for your help!
