### ISSUE TITLE
Designed a Case

### ISSUE THREAD

**Issue by rossiniscarface** [showmewebcam/showmewebcam#70]
Hi, 
thanks for the project. I am so exited, that i designed a new case for the camera which looks a bit different than the others. 

Lets have a look: 

[https://www.thingiverse.com/thing:4682726](https://www.thingiverse.com/thing:4682726)

**Comment by dgsiegel** [comment]
Awesome, just added it to our wiki: https://github.com/showmewebcam/showmewebcam/wiki/Cases

Thanks!
