### ISSUE TITLE
Feature Request: Provide a way to indicate when the camera is actively streaming

### ISSUE THREAD

**Issue by muffinresearch** [showmewebcam/showmewebcam#89]
As a new feature suggestion, is there any way to tell when the camera is actively streaming to software? Ideally I'd like a way to hook up an LED via a GPIO pin to show when the camera is actively streaming as opposed to just being powered up?

**Comment by dgsiegel** [comment]
Both is already possible: https://github.com/showmewebcam/showmewebcam#led-indicator
