### ISSUE TITLE
Auto Exposure Mode UVC Setting not standard-conform

### ISSUE THREAD

**Issue by dognotdog** [showmewebcam/showmewebcam#92]
On v1.70, `CT_AE_MODE_CONTROL 0x02` does not conform to UVC 1.5.

It shows up as 
```
autoExposureMode = {
    current = <00>;
    default = <00>;
    flags = 3;
    max = <03>;
    min = <00>;
    resolution = <01>;
}
```
though `resolution` is supposed to be a bitmap of modes available:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/1443151/105799532-c6b33880-5f62-11eb-913b-e8a90513aa9d.png">

I am not sure where this is handled, yet, it might be a `uvc-gadget` or kernel problem.

**Comment by dgsiegel** [comment]
You might want to move this issue to either https://github.com/peterbay/uvc-gadget or https://github.com/raspberrypi/linux/
