### ISSUE TITLE
Possible to use HDMI output?

### ISSUE THREAD

**Issue by fwahl711** [showmewebcam/showmewebcam#97]
First of all, thanks for your great work! I am looking into building a Raspberry webcam. However, I use an HDMI grabber/mixer device for my setup and thus, it would be nice if the HDMI output of the Pi would output the camera picture (and "only the picture", so no status bar or similar). Is this possible? Thanks and best, Florian

**Comment by dgsiegel** [comment]
I guess the best way to make use of this would be to use Raspbian, and share its screen via HDMI. We have disabled all graphics capability on the showmewebcam.
